blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DOpenCV_DIR=/usr/local/share/OpenCV
- -DDarknet_include_DIR=/home/whymatter/github.com/albatross/ros/src/third-party/darknet/src
- -DDarknet_link_DIR=/home/whymatter/github.com/albatross/ros/src/third-party/darknet
devel_layout: linked
devel_space: devel
extend_path: null
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
