// Generated by gencpp from file alb_ros_msgs/BoundingBox.msg
// DO NOT EDIT!


#ifndef ALB_ROS_MSGS_MESSAGE_BOUNDINGBOX_H
#define ALB_ROS_MSGS_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alb_ros_msgs
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : x(0)
    , y(0)
    , w(0)
    , h(0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , w(0)
    , h(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint32_t _w_type;
  _w_type w;

   typedef uint32_t _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::alb_ros_msgs::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::alb_ros_msgs::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::alb_ros_msgs::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alb_ros_msgs::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alb_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'alb_ros_msgs': ['/home/whymatter/github.com/albatross/ros/src/alb_ros_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1d7daec9dd3af1e73d39f873a977099";
  }

  static const char* value(const ::alb_ros_msgs::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1d7daec9dd3af1eULL;
  static const uint64_t static_value2 = 0x73d39f873a977099ULL;
};

template<class ContainerAllocator>
struct DataType< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alb_ros_msgs/BoundingBox";
  }

  static const char* value(const ::alb_ros_msgs::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32       x\n\
uint32       y\n\
uint32       w\n\
uint32       h\n\
";
  }

  static const char* value(const ::alb_ros_msgs::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alb_ros_msgs::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alb_ros_msgs::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALB_ROS_MSGS_MESSAGE_BOUNDINGBOX_H
