set(_CATKIN_CURRENT_PACKAGE "yolo_detector")
set(yolo_detector_VERSION "1.2.4")
set(yolo_detector_MAINTAINER "Oliver Seitz <seitz-oliver@gmx.de>")
set(yolo_detector_PACKAGE_FORMAT "2")
set(yolo_detector_BUILD_DEPENDS "alb_ros_base" "image_transport" "std_msgs" "sensor_msgs" "cv_bridge")
set(yolo_detector_BUILD_EXPORT_DEPENDS "alb_ros_base" "image_transport" "std_msgs" "sensor_msgs" "cv_bridge")
set(yolo_detector_BUILDTOOL_DEPENDS "catkin")
set(yolo_detector_BUILDTOOL_EXPORT_DEPENDS )
set(yolo_detector_EXEC_DEPENDS "alb_ros_base" "image_transport" "std_msgs" "sensor_msgs" "cv_bridge")
set(yolo_detector_RUN_DEPENDS "alb_ros_base" "image_transport" "std_msgs" "sensor_msgs" "cv_bridge")
set(yolo_detector_TEST_DEPENDS )
set(yolo_detector_DOC_DEPENDS )
set(yolo_detector_URL_WEBSITE "")
set(yolo_detector_URL_BUGTRACKER "")
set(yolo_detector_URL_REPOSITORY "")
set(yolo_detector_DEPRECATED "")