set(_CATKIN_CURRENT_PACKAGE "alb_msgs")
set(alb_msgs_VERSION "1.2.4")
set(alb_msgs_MAINTAINER "Oliver Seitz <seitz-oliver@gmx.de>")
set(alb_msgs_PACKAGE_FORMAT "2")
set(alb_msgs_BUILD_DEPENDS )
set(alb_msgs_BUILD_EXPORT_DEPENDS )
set(alb_msgs_BUILDTOOL_DEPENDS "catkin")
set(alb_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(alb_msgs_EXEC_DEPENDS )
set(alb_msgs_RUN_DEPENDS )
set(alb_msgs_TEST_DEPENDS )
set(alb_msgs_DOC_DEPENDS )
set(alb_msgs_URL_WEBSITE "")
set(alb_msgs_URL_BUGTRACKER "")
set(alb_msgs_URL_REPOSITORY "")
set(alb_msgs_DEPRECATED "")